### PR TITLE
also install signatures.{cmi,cmti}

### LINKED ISSUE #217: MPR#5243: Improve the API documentation
_PR transferred from https://caml.inria.fr/mantis/view.php?id=5243_
[original reporter: @Chris00]

Ideally, the API documentation for plugins should be more complete (basically serve as a reference how to write a plugin) and cross-referenced.
http://nicolaspouillard.fr/ocamlbuild/html/Signatures.PLUGIN.html

### PR DESCRIPTION
**Pull request by gasche**
Hopefully fixes #217.

### CODE REVIEW

**Comment by gasche** [comment]
In fact I was a bit too optimistic about the usability of those languages. OCaml pull-requests (that pull from ocamlbuild master) are now failing with:

```
cp META src/signatures.{mli,cmi,cmti} /home/travis/local/lib/ocamlbuild
cp: cannot stat `src/signatures.{mli,cmi,cmti}': No such file or directory
make[1]: *** [install-lib-basics] Error 1
```

Oh well. Will fix.

**Comment by whitequark** [comment]
@gasche How did this happen?

**Comment by dbuenzli** [comment]
Mmmh sorry about the merge then. It's strange the CI was saying yes. Is due to a lack `bin_annot` ?

**Comment by gasche** [comment]
I'm just as confused (no need to apologize!); `-bin-annot` is passed correctly (see the full [failing logs](https://travis-ci.org/ocaml/ocaml/jobs/208169496)), I wonder if this is just a case of the `foo.{bar,baz}` pattern not being expanded -- but I don't understand why that would be, might this be a bashism that some other shells don't support? I certainly cannot reproduce any install/uninstall issue on my machine.

**Comment by dbuenzli** [comment]
> I wonder if this is just a case of the foo.{bar,baz} pattern not being expanded -- but I don't understand why that would be, might this be a bashism

Actually when I saw it I wanted to comment that it is a bashism but then thaught that this might be supported by the `make` language. So yes, it is a bashism.

**Pull request merged**
