### PR TITLE
Update ocaml/setup-ocaml to v3

### PR DESCRIPTION
**Pull request by smorimoto**

### CODE REVIEW

**Comment by gasche** [comment]
Thanks! Why is there a dependabot file, can we do without it?

**Comment by smorimoto** [comment]
It's pretty annoying to keep manually bumping dependencies, and the goal is to automate with it. I could split it into different PR, but I was just lazy.

**Comment by gasche** [comment]
Forgive my ignorance, I am not used to dependabot. Which dependencies are we talking about? Maybe the dependencies of the github workflow definitions? (which are what? `setup-ocaml`?)

**Comment by smorimoto** [comment]
Yes, Dependabot takes care of version control for GitHub Actions in this case. It automatically opens a PR whenever a new version is released.

**Comment by smorimoto** [comment]
Real world example: https://github.com/ocsigen/tyxml/pull/338

**Comment by kit-ty-kate** [comment]
Thanks!

**Pull request merged**
