### PR TITLE
Add MSVC testing

### PR DESCRIPTION
**Pull request by dra27**
Some work needed on the testsuite, but starting to build on the truly astounding work already done on Windows support here!

Should fix #323 as we're now testing msvc

### CODE REVIEW

**Comment by hhugo** [comment]
I've pushed changes to the testsuite. CI is now happy

**Comment by hhugo** [comment]
One still need to properly fix conditional steps in the CI

**Comment by gasche** [comment]
The PR as-is looks fairly clean (unlike some intermediate iterations); congratulations are due to @dra27 and @hhugo. Isn't this ready for review?

**Comment by hhugo** [comment]
No, I'm unhappy about the conditional step change in the ci

**Comment by hhugo** [comment]
@gasche, this is now ready.

**Comment by dra27** [comment]
Thanks, @hhugo - you got the fixes in for the testsuite before I'd had a chance to finish my version locally! Technically [c664696](https://github.com/ocaml/ocamlbuild/pull/347/commits/c6646961e8f0a34a914af80ce07c1b9a54cfb6a0) is not part of restoring MSVC - I don't know if you'd prefer that to be a in a separate PR?

**Review by gasche — APPROVED** [review]
The mix of `"foo" -.- bar` and `"foo." ^ bar` in the testsuite is a bit jarring (it took me a few dozen seconds to convince myself than no, they were strictly equivalent), but maybe we can tolerate this if you find it cumbersome to cleanup, and generally the patch is nice to read. I am okay with having the commit that adds .exe to the install script as part of this PR.

**Comment by hhugo** [comment]
> The mix of `"foo" -.- bar` and `"foo." ^ bar` in the testsuite is a bit jarring (it took me a few dozen seconds to convince myself than no, they were strictly equivalent), but maybe we can tolerate this if you find it cumbersome to cleanup, and generally the patch is nice to read. I am okay with having the commit that adds .exe to the install script as part of this PR.

fixed

**Pull request merged**
