### PR TITLE
Test more downstream code on CI

### PR DESCRIPTION
**Pull request by whitequark**

### CODE REVIEW

**Comment by gasche** [comment]
While we are at it, could we have an `ocb_stubblr`-using dependency? It would make sense to have one dependency for all non-trivial ocamlbuild plugins out there: cppo also comes to mind; there is also the namespace-as-ocamlbuild plugin, but I don't know if it is used in opam-released packages, and Solvuu (again, not sure).

**Comment by whitequark** [comment]
> While we are at it, could we have an ocb_stubblr-using dependency? It would make sense to have one dependency for all non-trivial ocamlbuild plugins out there: cppo also comes to mind

Added both.

> Solvuu (again, not sure).

The dependencies seem quite heavy (they all need core_kernel...)

**Comment by gasche** [comment]
Ok, this sounds like a nice compromise. Feel free to merge once we get CI results or whenever.

**Comment by gasche** [comment]
(Are you the kind of person that prefer other people to merge their PRs, or to have a chance to do a last amending round before merging themselves?)

**Comment by whitequark** [comment]
> (Are you the kind of person that prefer other people to merge their PRs, or to have a chance to do a last amending round before merging themselves?)

It does not matter to me very much. Unless explicitly noted my PR commit stacks are always ready to merge; I rebase before every push.

**Pull request merged**
