### PR TITLE
Add flags afl_instrument and afl_inst_ratio.

### PR DESCRIPTION
**Pull request by yallop**
See https://github.com/ocaml/ocaml/pull/504.

### CODE REVIEW

**Comment by whitequark** [comment]
@yallop Could you add a changelog entry?

**Comment by gasche** [comment]
Now that ocamlbuild versions are dissociated from ocaml versions, a delicate problem arises: how should we handle OCaml features that are only supported in some of the versions that ocamlbuild support? This is, of course, not specific to this PR, but as far as I know this is the first PR raising this issue.

We could either have enough logic in the ocamlbuild rules to not add the flags on unsupported OCaml versions (that may make more sense in some cases than others; for `-bin-annot` I think that silently ignoring the flag would be ok, but for `-afl-fuzz` it is not as clear), or aggressively update the required OCaml versions for ocamlbuild whenever we add support for new OCaml compiler flags. Or a mix of the two. What do we think?

**Comment by whitequark** [comment]
> or aggressively update the required OCaml versions for ocamlbuild whenever we add support for new OCaml compiler flags.

This basically leaves out dry everyone on older OCaml versions with respect to bugfixes. For example, we've recently introduced a compile time regression with `.mldylib` files. If we bump the version requirement now, everyone using 4.04 or earlier will get stuck with a slower ocamlbuild (or, if they install an even older version, with a buggier ocamlbuild...)

> We could either have enough logic in the ocamlbuild rules to not add the flags on unsupported OCaml versions (that may make more sense in some cases than others; for -bin-annot I think that silently ignoring the flag would be ok, but for -afl-fuzz it is not as clear)

It seems unlikely that afl_fuzz will be used in any way but a carefully controlled one during a QA process, so it might not even be necessary to gate it in any way. I propose deferring this decision until we are up the wall against it :-)

**Comment by gasche** [comment]
> This basically leaves out dry everyone on older OCaml versions with respect to bugfixes. 

We *could* consider maintaining bugfix branches.

>  I propose deferring this decision until we are up the wall against it :-)

Ok.

I have no other comment on the PR and would be in favor of merging once we have the changelog entry.

**Comment by whitequark** [comment]
> We could consider maintaining bugfix branches.

I am strongly against that. It is a large amount of work, and a larger than necessary amount of difficult decisions on whether this work should be done for a certain compiler version. Adding cppo annotations, while certainly ugly (and introducing a circular dependency), clearly has much less cumulative overhead.

**Comment by yallop** [comment]
> @yallop Could you add a changelog entry?

Done: see e234958.

**Comment by gasche** [comment]
I don't think we need preprocessing in this case, because we can express the conditional test in pure OCaml code (this is not about using language features that older compiler would barf on); see [this in Batteries' myocamlbuild.ml](https://github.com/ocaml-batteries-team/batteries-included/blob/4f10969/myocamlbuild.ml#L219-L223) for an example:

```
      if ocaml_version = (4, 0) then begin
        (* OCaml 4.00 has -bin-annot but no ocamlbuild flag *)
        flag ["ocaml"; "bin_annot"; "compile"] (A "-bin-annot");
        flag ["ocaml"; "bin_annot"; "pack"] (A "-bin-annot");
end;
```

(This particular test is precisely on 4.00 because it implements a flag that exists in ocamlbuild 4.01 and above for a feature introduced in 4.00. In the ocamlbuild codebase itself those would be comparison rather than equality tests.)

**Comment by whitequark** [comment]
Oh! I have not realized that we have `ocaml_version`; but indeed even if we did not, it would be simpler to add it than to drag in cppo.

**Comment by yallop** [comment]
I just realised that I added the changelog entry to the wrong section -- sorry!  Fixed in #235.

**Pull request merged**
