### PR TITLE
Opam: configure step before build

### PR DESCRIPTION
**Pull request by gasche**
This PR is a candidate for a release-ready opam/Makefile combination for ocamlbuild. It should supersede #38, but I'd like to get the opinion of people that know about these things to be sure that it really is better.

### CODE REVIEW

**Comment by gasche** [comment]
Of course I had forgotten to include a file, [Makefile.configure](https://github.com/ocaml/ocamlbuild/pull/41/files#diff-28c00655e33412d7954b7c37951239aa), which performs the actual configuration step (this is the `./configure` in GNU make mentioned by @bobot in #38 ).

**Comment by gasche** [comment]
I also checked that this PR solves #40 , simply by changing the way `LIBDIR` is defined in `ocamlbuild_config.ml`.

**Comment by gasche** [comment]
@adrien-n I'm planning to merge this PR shortly on the basis of your review. Any last words?

**Comment by adrien-n** [comment]
No, nothing to add besides http://caml.inria.fr/mantis/view.php?id=7116 ( "Allow easy retrieval of Makefile.config's values" ) which would be nice to have first.

**Pull request merged**
