### PR TITLE
Propagate -keep-locs and -keep-docs in all compiler invocations

### LINKED ISSUE #256: Tags "keep_docs" and "keep_locs" not honored when using ".mlpack"s
Hello,

When tag `keep_docs` (resp. `keep_locs`) is used, `ocamlc -pack` is called without `-keep-docs` (resp. `-keep-locs`) option.

[This gist](https://gist.github.com/jacquev6/2c5d711d11243185205ec0a49e542a1d) is a minimal example showing the issue and proving that `ocamlc -pack -keep-docs` *does* keep the docs in the produced `.mli` file.

I might dive into ocamlbuild to provide a fix for that, but I wanted to report it first, in case it's a one-hour fix for someone who knows how.

Thanks!

### PR DESCRIPTION
**Pull request by gasche**
Fixes #256

### CODE REVIEW

**Comment by jacquev6** [comment]
Thanks! That was quick :)

**Comment by jacquev6** [comment]
That was quick but this doesn't work :-/ Using the gist I linked in #256, after path-pinning the `keep-locs-docs` branch:

    $ ./do.sh 
    /home/vincent/.opam/4.05.0/bin/ocamldep.opt -keep-docs -pp -keep-docs -modules Content.mli > Content.mli.depends
    + /home/vincent/.opam/4.05.0/bin/ocamldep.opt -keep-docs -pp -keep-docs -modules Content.mli > Content.mli.depends
    /home/vincent/.opam/4.05.0/bin/ocamldep.opt: unknown option '-keep-docs'.

Looks like adding `flag ["ocaml"; "pack"; "keep_docs";] (A "-keep-docs");` and  `flag ["ocaml"; "pack"; "keep_locs";] (A "-keep-locs");` would work.

**Comment by gasche** [comment]
Indeed. I tried to go for a broader scope of flag application to avoid under-shooting, but I forgot about the `ocamldep` invocation. I need a new iteration and a testing strategy.

**Comment by jacquev6** [comment]
Thank you for your time!

**Comment by gasche** [comment]
I would like to write a testsuite but I don't know of any easy-to-implement way to automate the check that `keep-loc` is passed with our current testsuite. The only thing I found was that if I compile a pack from several modules, then edit one of the `.mli` to add a new empty line at the start, then location changes and the hash of the result packed `.cmi` should change as a result. But our testsuite encourages us to perform a single build action and observe the result (or build error), so this is impractical. I think I will leave this without a unit test.

**Comment by jacquev6** [comment]
Thanks! I'm using it with

    opam pin add ocamlbuild https://github.com/gasche/ocamlbuild.git#keep-locs-docs

and everything looks fine.

**Comment by gasche** [comment]
Merged, thanks a lot for the report and feedback.

**Pull request merged**
