### PR TITLE
Update changelog

### PR DESCRIPTION
**Pull request by hhugo**
on top of #334 #344

### CODE REVIEW

**Comment by hhugo** [comment]
We can release ocamlbuild after this PR is merged and close #322

**Comment by hhugo** [comment]
This is ready for review

**Comment by gasche** [comment]
My understanding is that you ( @hhugo ) have integrated most of the patches from the fdopen repository, and that we believe that the remaining one are not necessary anymore for ocamlbuild to work correctly on Windows. Thanks! Splitting them up, discussing them together and cleaning them up when possible was the right move, I think, and I'm glad I could help from the sidelines.

Do you have an idea of which of the several Windows configurations are known to work correctly for ocamlbuild now? (Do we expect ocamlbuild to work well with or without cygwin? does msvc-or-mingw play any role?)

**Comment by hhugo** [comment]
> Do you have an idea of which of the several Windows configurations are known to work correctly for ocamlbuild now? (Do we expect ocamlbuild to work well with or without cygwin? does msvc-or-mingw play any role?)

What work is what we have in the CI. That is native windows with mingw. I would expect the msys2 setup to work as well (based on the [comment](https://github.com/ocaml/ocamlbuild/pull/339#discussion_r1647804070 from @dra27)

For the cygwin variant, my understanding is that one must use the fdopen repo which is full of patches making it hard to reason about things. What does that mean to be working in that setup ? What set of opam-repo to use ?
I could try to bring back some CI jobs for this setup. Is it still possible with setup-ocaml.3 ?

For the msvc port, I've no idea what to expect. @dra27 can you help here ? is opam supposed to work out of the box in that setup ?

**Comment by gasche** [comment]
Thanks for the clarifications!

Note that I am not myself asking for any particular configuration to work, I was just wondering what the current status is.

**Comment by hhugo** [comment]
#347 demonstrate that msvc is working.
So we have:
- mingw ok
- msvc ok
- cygwin untested, setup-ocaml doesn't support this setup.

**Pull request merged**
